version: '3.3'

services:

    ### Dev Website Container #################################

    # project:
    #     build:
    #         context: ./project
    #     volumes:
    #         - ./project/ear:/var/www/html/project/
    #         - ~/.aws:/.aws
    #     ports:
    #         - "7005:80"
    #     privileged: true
    #     hostname: project

    ### MariaDB Container #######################################

    mysql:
        build: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql/lib/mysql:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/init:/docker-entrypoint-initdb.d
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: earDB
            MYSQL_PASSWORD: udn123
            MYSQL_ROOT_PASSWORD: password

    ### redis container #############

    redis:
        image: redis
        ports:
            - 6379:6379

    #### sonarqube container #########

    sonarqube:
        image: sonarqube
        ports:
            - 9000:9000

    #### MQTT Container ####
    # docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto
    mosquitto:
        image: eclipse-mosquitto
        volumes:
            - ./config/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports:
            - 1883:1883
            - 9001:9001
    #### RabbitMQ Container ####
    # docker run --name myrabbitmq -p 15672:15672 -p 5672:5672 -d rabbitmq:management
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 15672:15672
            - 5672:5672
    # # ### Wordpress Container #######################################
    #     db:
    #         image: mysql:5.7
    #         restart: always
    #         environment:
    #             MYSQL_ROOT_PASSWORD: somewordpress
    #             MYSQL_DATABASE: wordpress
    #             MYSQL_USER: wordpress
    #             MYSQL_PASSWORD: wordpress
    #     wordpress:
    #         depends_on:
    #             - db
    #         image: wordpress:latest
    #         volumes:
    #             - ./wordpress_data:/var/www/html
    #         ports:
    #             - "8000:80"
    #         restart: always
    #         environment:
    #             WORDPRESS_DB_HOST: db
    #             WORDPRESS_DB_USER: wordpress
    #             WORDPRESS_DB_PASSWORD: wordpress
    #             WORDPRESS_DB_NAME: wordpress
